package com.sena.crud.ui.screen
import android.util.Patterns
import androidx.compose.foundation.layout.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.runtime.saveable.rememberSaveable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.input.PasswordVisualTransformation
import androidx.compose.ui.unit.dp
import com.sena.crud.ui.component.*
import com.sena.crud.ui.state.AuthUiState
@Composable fun StartScreen(onLogin:()->Unit,onRegister:()->Unit,configured:Boolean){Column(Modifier.fillMaxSize().padding(24.dp),verticalArrangement=Arrangement.Center,horizontalAlignment=Alignment.CenterHorizontally){Text("Gestor personal de tareas",style=MaterialTheme.typography.headlineMedium);Spacer(Modifier.height(24.dp));if(!configured){Text("Firebase no está configurado. Agrega google-services.json.",color=MaterialTheme.colorScheme.error);Spacer(Modifier.height(16.dp))};Button(onLogin,enabled=configured,modifier=Modifier.fillMaxWidth()){Text("Iniciar sesión")};Spacer(Modifier.height(10.dp));OutlinedButton(onRegister,enabled=configured,modifier=Modifier.fillMaxWidth()){Text("Crear cuenta")}}}
@Composable private fun PasswordField(v:String,onV:(String)->Unit,label:String)=OutlinedTextField(v,onV,label={Text(label)},modifier=Modifier.fillMaxWidth(),singleLine=true,visualTransformation=PasswordVisualTransformation())
@Composable fun LoginScreen(s:AuthUiState,back:()->Unit,login:(String,String)->Unit,register:()->Unit){var e by rememberSaveable{mutableStateOf("")};var p by rememberSaveable{mutableStateOf("")};var err by remember{mutableStateOf<String?>(null)};Column(Modifier.fillMaxSize().padding(24.dp),verticalArrangement=Arrangement.Center){Text("Iniciar sesión",style=MaterialTheme.typography.headlineMedium);Spacer(Modifier.height(18.dp));AppTextField(e,{e=it},"Correo");Spacer(Modifier.height(10.dp));PasswordField(p,{p=it},"Contraseña");Spacer(Modifier.height(12.dp));err?.let{Text(it,color=MaterialTheme.colorScheme.error)};s.errorMessage?.let{Text(it,color=MaterialTheme.colorScheme.error)};Spacer(Modifier.height(12.dp));LoadingButton("Entrar",s.isLoading){err=when{e.isBlank()||p.isBlank()->"Todos los campos son obligatorios.";!Patterns.EMAIL_ADDRESS.matcher(e).matches()->"Ingresa un correo válido.";else->null};if(err==null)login(e,p)};TextButton(register){Text("Crear una cuenta")};TextButton(back){Text("Volver")}}}
@Composable fun RegisterScreen(s:AuthUiState,back:()->Unit,register:(String,String)->Unit,login:()->Unit){var e by rememberSaveable{mutableStateOf("")};var p by rememberSaveable{mutableStateOf("")};var c by rememberSaveable{mutableStateOf("")};var err by remember{mutableStateOf<String?>(null)};Column(Modifier.fillMaxSize().padding(24.dp),verticalArrangement=Arrangement.Center){Text("Crear cuenta",style=MaterialTheme.typography.headlineMedium);Spacer(Modifier.height(18.dp));AppTextField(e,{e=it},"Correo");Spacer(Modifier.height(10.dp));PasswordField(p,{p=it},"Contraseña");Spacer(Modifier.height(10.dp));PasswordField(c,{c=it},"Confirmar contraseña");Spacer(Modifier.height(12.dp));err?.let{Text(it,color=MaterialTheme.colorScheme.error)};s.errorMessage?.let{Text(it,color=MaterialTheme.colorScheme.error)};Spacer(Modifier.height(12.dp));LoadingButton("Registrarme",s.isLoading){err=when{e.isBlank()||p.isBlank()||c.isBlank()->"Todos los campos son obligatorios.";!Patterns.EMAIL_ADDRESS.matcher(e).matches()->"Ingresa un correo válido.";p.length<6->"La contraseña debe tener mínimo 6 caracteres.";p!=c->"Las contraseñas no coinciden.";else->null};if(err==null)register(e,p)};TextButton(login){Text("Ya tengo una cuenta")};TextButton(back){Text("Volver")}}}
