package com.sena.crud.ui.screen
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import com.sena.crud.domain.model.*
import com.sena.crud.ui.component.AppTextField
import com.sena.crud.ui.state.*
@Composable fun TaskListScreen(s:TaskListUiState,email:String?,add:(String,String)->Unit,edit:(Task,String,String,Boolean)->Unit,del:(Task)->Unit,logout:()->Unit,drafts:()->Unit){var editing by remember{mutableStateOf<Task?>(null)};var deleting by remember{mutableStateOf<Task?>(null)};var create by remember{mutableStateOf(false)};Column(Modifier.fillMaxSize().padding(16.dp)){Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Column{Text("Mis tareas",style=MaterialTheme.typography.headlineSmall);Text(email.orEmpty(),style=MaterialTheme.typography.bodySmall)};TextButton(logout){Text("Salir")}};Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(8.dp)){Button({create=true},Modifier.weight(1f)){Text("Nueva")};OutlinedButton(drafts,Modifier.weight(1f)){Text("Borradores")}};Spacer(Modifier.height(12.dp));if(s.isLoading)LinearProgressIndicator(Modifier.fillMaxWidth());s.errorMessage?.let{Text(it,color=MaterialTheme.colorScheme.error)};if(!s.isLoading&&s.tasks.isEmpty())Text("No tienes tareas publicadas.",Modifier.padding(top=24.dp));LazyColumn(verticalArrangement=Arrangement.spacedBy(10.dp)){items(s.tasks,key={it.id}){t->Card(Modifier.fillMaxWidth()){Column(Modifier.padding(14.dp)){Text(t.title,style=MaterialTheme.typography.titleLarge);Text(t.description);Text(if(t.completed)"Completada" else "Pendiente");Row{TextButton({editing=t}){Text("Editar")};TextButton({deleting=t}){Text("Eliminar")}}}}}}};if(create)TaskEditorDialog(null,{create=false}){t,d,_->create=false;add(t,d)};editing?.let{t->TaskEditorDialog(t,{editing=null}){title,d,c->editing=null;edit(t,title,d,c)}};deleting?.let{t->AlertDialog({deleting=null},title={Text("Eliminar tarea")},text={Text("¿Seguro que quieres eliminarla?")},confirmButton={TextButton({deleting=null;del(t)}){Text("Eliminar")}},dismissButton={TextButton({deleting=null}){Text("Cancelar")}})}}
@Composable fun DraftListScreen(s:DraftListUiState,back:()->Unit,new:()->Unit,edit:(TaskDraft)->Unit,del:(TaskDraft)->Unit,publish:(TaskDraft)->Unit){Column(Modifier.fillMaxSize().padding(16.dp)){Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Text("Borradores",style=MaterialTheme.typography.headlineSmall);TextButton(back){Text("Volver")}};Button(new,Modifier.fillMaxWidth()){Text("Nuevo borrador")};Spacer(Modifier.height(12.dp));if(s.isLoading)LinearProgressIndicator(Modifier.fillMaxWidth());s.errorMessage?.let{Text(it,color=MaterialTheme.colorScheme.error)};if(!s.isLoading&&s.drafts.isEmpty())Text("No hay borradores locales.",Modifier.padding(top=24.dp));LazyColumn(verticalArrangement=Arrangement.spacedBy(10.dp)){items(s.drafts,key={it.id}){d->Card(Modifier.fillMaxWidth()){Column(Modifier.padding(14.dp)){Text(d.title,style=MaterialTheme.typography.titleLarge);Text(d.description);Row{TextButton({edit(d)}){Text("Editar")};TextButton({publish(d)}){Text("Publicar")};TextButton({del(d)}){Text("Eliminar")}}}}}}}}
@Composable fun TaskEditorDialog(task:Task?,dismiss:()->Unit,save:(String,String,Boolean)->Unit){var t by remember(task?.id){mutableStateOf(task?.title.orEmpty())};var d by remember(task?.id){mutableStateOf(task?.description.orEmpty())};var c by remember(task?.id){mutableStateOf(task?.completed?:false)};var err by remember{mutableStateOf<String?>(null)};AlertDialog(dismiss,title={Text(if(task==null)"Nueva tarea" else "Editar tarea")},text={Column{AppTextField(t,{t=it},"Título");Spacer(Modifier.height(8.dp));AppTextField(d,{d=it},"Descripción",singleLine=false);if(task!=null)Row{Checkbox(c,{c=it});Text("Completada",Modifier.padding(top=12.dp))};err?.let{Text(it,color=MaterialTheme.colorScheme.error)}}},confirmButton={TextButton({if(t.isBlank())err="El título es obligatorio." else save(t,d,c)}){Text("Guardar")}},dismissButton={TextButton(dismiss){Text("Cancelar")}})}
@Composable fun DraftEditorDialog(draft:TaskDraft?,dismiss:()->Unit,save:(String,String)->Unit){var t by remember(draft?.id){mutableStateOf(draft?.title.orEmpty())};var d by remember(draft?.id){mutableStateOf(draft?.description.orEmpty())};var err by remember{mutableStateOf<String?>(null)};AlertDialog(dismiss,title={Text(if(draft==null)"Nuevo borrador" else "Editar borrador")},text={Column{AppTextField(t,{t=it},"Título");Spacer(Modifier.height(8.dp));AppTextField(d,{d=it},"Descripción",singleLine=false);err?.let{Text(it,color=MaterialTheme.colorScheme.error)}}},confirmButton={TextButton({if(t.isBlank())err="El título es obligatorio." else save(t,d)}){Text("Guardar")}},dismissButton={TextButton(dismiss){Text("Cancelar")}})}
